#!/bin/sh
set -e

# Tag to allow some debhelper commands to inject relevant code
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/default/kdm.d/10_desktop-base 9.0.0~ desktop-base -- "$@"
# End automatically added section


if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if which update-grub2 > /dev/null ; then
        update-grub2 || true
    fi
fi

